version: "3.2"
services:
  web:
    build: docker/nginx
    image: oursociety/web:dev
    networks: [ public, internal ]
    ports: [ "80:80" ]
    volumes: [ "./webroot:/app/webroot:ro" ]
  app:
    build: docker/php
    image: oursociety/app:dev
    networks: [ internal, secure ]
    ports: [ "9000:9000" ]
    volumes: [ ".:/app:rw" ]
  db:
    build: docker/mysql
    image: oursociety/db:dev
    networks: [ secure ]
    ports: [ "3306:3306" ]
  mail:
    build: docker/mailhog
    image: oursociety/mail:dev
    networks: [ internal ]
    ports: [ "1025:1025", "8025:8025" ]
#  assets:
#    build: docker/webpack
#    image: oursociety/assets:dev
#    networks: [ public ]
#    volumes: [ ".:/app:rw", "/app/node_modules", "~/.cache/yarn/:/root/.cache/yarn/:ro" ]
networks:
  public: {}
  internal: {}
  secure: {}
