version: 2
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy_staging:
          requires: [ build ]

jobs:
  build:
    docker:
      - image: deizel/circleci-php:7.1-fpm-node-browsers
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: app
          MYSQL_PASSWORD: secret
          MYSQL_DATABASE: oursociety_test
    steps:
      - checkout
      - restore_cache:
          name: Restore Node Modules From Cache
          key: yarn-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install Node Modules
          command: |
            yarn install
      - run:
          name: Compile Assets
          command: |
            yarn prod
      - save_cache:
          name: Save Node Modules To Cache
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Remove Node Modules
          command: |
            rm -rf node_modules
      - restore_cache:
          name: Restore Composer Packages From Cache
          key: composer-v1-{{ checksum "composer.lock" }}
      - run:
          name: Install Production Composer Packages
          command: |
            composer install --optimize-autoloader --prefer-dist --no-interaction --no-dev --no-progress
      - run:
          name: Create Artifacts
          command: |
            mkdir /tmp/artifacts
            tar czf /tmp/artifacts/oursociety-production.tar.gz --exclude=".+" .
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Install Development Composer Packages
          command: |
            composer install --optimize-autoloader --prefer-dist --no-interaction --no-progress
      - save_cache:
          name: Save Composer Packages To Cache
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - ~/.composer/cache
      - run:
          name: Check MySQL Connection
          command: |
            dockerize -wait tcp://:3306
      - run:
          name: Set sql_mode setting on MySQL
          command: mysql -u root -proot -h 127.0.0.1 -e "SET GLOBAL sql_mode = (SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY',''));"
      - run:
          name: Configure Hosts
          command: |
            echo "127.0.0.1 oursociety.test" | sudo tee -a /etc/hosts
      - run:
          name: Configure Web Server
          command: |
            sudo cp .circleci/nginx.conf /etc/nginx/sites-available/default
      - run:
          name: Start Web Server
          command: |
            sudo /etc/init.d/nginx start
      - run:
          name: Start PHP Server
          command: |
            sudo php-fpm --daemonize
      - run:
          name: Configure Test Environment
          command: |
            cp .env.test.default .env.test
      - run:
          name: Seed Test Database
          command: |
            bin/cake fixtures restore
            bin/cake fixtures migrate
      - run:
          name: Fix Permissions
          command: |
            sudo chmod -Rv 777 logs tmp
      - run:
          name: Output Application Homepage
          command: |
            STATUSCODE=$(curl --silent --output /dev/stderr --write-out "%{http_code}" http://oursociety.test/)

            if test $STATUSCODE -ne 200; then
                exit 1
            fi
      - run:
          name: Run Acceptance Tests
          command: |
            vendor/bin/behat --no-snippets --profile=circleci --strict -vv features/guest/navigation.feature
  deploy_staging:
    docker:
      - image: williamyeh/ansible:ubuntu16.04
    steps:
      - run:
          name: Add github.com SSH key
          command: mkdir ~/.ssh && chmod 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Install necessary packages
          command: apt-get update && apt-get install git sudo python python-pip python-dev -y && pip install -U boto
      - run:
          name: Checkout ansible infrastructure repo
          command: git clone --recursive https://$GITHUB_AUTH_TOKEN@github.com/OurSociety/oursociety-infra.git ~/oursociety-infra
      - run:
          name: Create vault password file
          working_directory: ~/oursociety-infra
          command: echo $ANSIBLE_VAULT_PASS > .vault
      - run:
          name: Drop SSH key for oursociety deployment
          working_directory: ~/oursociety-infra
          command: ansible-vault view secrets/key > ~/.ssh/oursociety.key && chmod 0600 ~/.ssh/oursociety.key
      - run:
          name: Run a deploy to the test vhost 
          working_directory: ~/oursociety-infra
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              ansible-playbook playbooks/deploy_service.yml -e "deploy_env=prod service=www deploy_target=test" --skip-tags 'common,iptables,www_php'
            fi
      - run:
          name: Run a deploy to the production vhost
          working_directory: ~/oursociety-infra
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ansible-playbook playbooks/deploy_service.yml -e "deploy_env=prod service=www deploy_target=prod" --skip-tags 'common,iptables,www_php'
            fi
      - run:
          name: Remove secrets
          command: rm -rf ~/.ssh ~/.bash_profile
