# Official build of MySQL - https://hub.docker.com/_/mysql/
#
# Version follows the latest version of MySQL on Amazon RDS in US East (N. Virginia) region:
#
# http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.VersionMgmt
FROM mysql:5.7.17

# Hard-coded credentials for development
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=app
ENV MYSQL_USER=app
ENV MYSQL_PASSWORD=secret
