<?php
declare(strict_types=1);

namespace OurSociety\View\Widget;

use BootstrapUI\View\Widget\BasicWidget;
use Cake\View\Form\ContextInterface;
use Cake\View\Widget\WidgetInterface as Widget;

class ZipWidget extends BasicWidget implements Widget
{
    public function render(array $data, ContextInterface $context)
    {
        $data = ['type' => 'text'] + $data + [
            'pattern' => '(\d{5}([\-]\d{4})?)',
            'v-input-mask' => '99999[-9999]',
            'title' => 'ZIP codes should be 5-digits (e.g. 07001), optionally with 4 extra digits (e.g. 07001-0101)',
        ];

        return parent::render($data, $context); // @todo Change the autogenerated stub
    }
}
